services:
  web:
    build: .
    image: personal_website_image:1.0.0
    container_name: personal_website
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    networks:
      - my_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always

networks:
  my_network:
    driver: bridge
